language: ruby
rvm:
  - 1.9.3
before_install:
  - gem install bundler --no-ri --no-rdoc -v "~> 1.17"
  - bundle install
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"
  - "psql -c 'create database thinking_sphinx;' -U postgres > /dev/null"
script: bundle exec appraisal rspec
env:
  - SPHINX_BIN=/usr/local/sphinx-2.0.9/bin/ SPHINX_VERSION=2.0.9 DATABASE=mysql2
  - SPHINX_BIN=/usr/local/sphinx-2.0.9/bin/ SPHINX_VERSION=2.0.9 DATABASE=postgresql
gemfile:
  - gemfiles/binary.gemfile
  - gemfiles/sphinxql.gemfile
